on:
  create

env:
  DO_NOT_FORMAT: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-latest]
        exe: [target/workflow-dev/resume-builder, target/workflow-dev/resume-builder.exe]
        exclude:
          - os: macos-latest
            exe: target/workflow-dev/resume-builder.exe
          - os: ubuntu-latest
            exe: target/workflow-dev/resume-builder.exe
          - os: windows-2019
            exe: target/workflow-dev/resume-builder
    steps:
    - uses: actions/checkout@v3.5.3

    - name: Nightly
      run: rustup install nightly

    - name: Cargo Check
      run: cargo check

    # - uses: Swatinem/rust-cache@v2
    #   with:
    #     shared-key: "default"
    #     key: "default"
    #     cache-on-failure: "true"
    
    - name: Build
      run: cargo build --profile workflow-dev

    - name: Run UPX
      continue-on-error: true
      uses: crazy-max/ghaction-upx@v3
      with:
        version: latest
        files: ${{ matrix.exe }}
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ matrix.exe }}
